services:
  - type: web
    name: coursework-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: olacoursework
      - key: PORT
        value: 3000
